### ISSUE TITLE
Variable support of year, month and day

### ISSUE THREAD

**Issue by harikt** [pmjones/CastRoute#1]
In the example provided at https://github.com/pmjones/CastRoute?tab=readme-ov-file#route-dumping

```
/archive/{username}[/{year:year}[/{month:month}[/{day:day}]]]
```

What I understood is this will only support variables as 

```
array: [^/]+
bool: 0|f|false|n|no|1|t|true|y|yes
float: \d+\.?\d+
int: \d+
mixed: [^/]+
string: [^/]+
```

So year, month and day in the above example need to be changed to int or regex format itself I believe. Am I correct here ?

**Comment by pmjones** [comment]
Ah yes, I copied those from the tests, where year/month/day are defined in a custom route variables class. Will fix. Thanks!

**Comment by harikt** [comment]
cool.
